name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Build docs
        run: pixi r --environment=docs docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./mybook/_build/html # Path to the build directory
          publish_branch: gh-pages # The branch where the book will be deployed
          user_name: "Matt Haberland"
          user_email: "mhaberla@calpoly.edu"
